### PR TITLE
task: sorting list of patch files

### PR DESCRIPTION
**Pull request by yannicklamprecht**
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()
There is no guarantee that the name strings in the resulting array will
appear in any specific order; they are not, in particular, guaranteed to
appear in alphabetical order.

Contains following changes:

- sorting of listed files Banause they aren't sorted by default. See message above.
- Updated the readme to reflect build steps
- Also filter away paths with `build/classes` (unix path sep) instead of only `build\\classes` (window path sep)
- Add Paper API to the fake project as dependency
- Updated to later paper build, patches can be dropped if preferred

### CODE REVIEW

**Comment by yannicklamprecht** [comment]
Updated to latest Paper upstream.

**Comment by MiniDigger** [comment]
cherry picked tons of stuff:
https://github.com/MiniDigger/Toothpick/commit/2109f01769e77c2efaa2f39c474e039a234e3886
https://github.com/MiniDigger/Toothpick/commit/bb194b8de9546b31064d1f658db8064800f09b26
https://github.com/MiniDigger/Toothpick/commit/6b10c6acaa8d57e0d92fe9186ad57915d27fef31

**Comment by yannicklamprecht** [comment]
Thanks.

**Comment by yannicklamprecht** [comment]
https://github.com/MiniDigger/Toothpick/commit/6b10c6acaa8d57e0d92fe9186ad57915d27fef31#diff-4da4cbcb3ac3aff042b9eb023460c120R134-R137

Should be:

```
!( file.absolutePath.contains("build/classes")  ||  file.absolutePath.contains("build\\classes") )
```
If one ore the other is in path then do not keep it in list.

**Pull request closed without merging**
